import { Const } from "Const.slint";
import { WindowBase } from "WindowBase.slint";

export component GameStatsWindow inherits WindowBase {
    default-font-family: Const.default-font-family;
    default-font-size: Const.default-font-size;
    background: Const.border-color;

    in property<int> count;
    in property<int> total;

    VerticalLayout {
        Text {
            text: "Stats";
            horizontal-alignment: center;
            vertical-alignment: center;
            color: Const.title-color;
            height: Const.title-height;
        }

        Rectangle {
            background: Const.content-background;
            border-color: Const.border-color;
            border-width: Const.border-width;
            border-radius: 2 * Const.border-width;

            Text {
                text: "Hits: \{root.count}/\{root.total}";
            }
        }
    }
}
