import { AboutSlint } from "std-widgets.slint";

import { Const } from "Const.slint";
import { WindowBase } from "WindowBase.slint";

export component PoweredByWindow inherits WindowBase {
    default-font-family: Const.default-font-family;
    default-font-size: Const.default-font-size;
    background: Const.border-color;

    VerticalLayout { 
        Text {
            text: "Powered By";
            horizontal-alignment: center;
            vertical-alignment: center;
            color: Const.title-color;
            height: Const.title-height;
        }

        rect := Rectangle {
            background: Const.content-background;
            border-color: Const.border-color;
            border-width: Const.border-width;
            border-radius: 2 * Const.border-width;

            GridLayout { 
                width: rect.width - 2 * rect.border-width;
                padding: Const.border-width;
                spacing: Const.border-width;

                Row {
                    Image {
                        source: @image-url("image/rust.svg");
                    }

                    Image {
                        source: @image-url("image/wgpu.png");
                    }
                }

                Row {
                    Image {
                        source: @image-url("image/openxr.svg");
                    }

                    AboutSlint {
                    }
                }
            }
        }
    }
}
