import "font/NotoSans-Regular.ttf";

export { AboutWindow } from "AboutWindow.slint";
export { GameStatsWindow } from "GameStatsWindow.slint";
export { PoweredByWindow } from "PoweredByWindow.slint";
export { SearchWindow } from "SearchWindow.slint";
export { StatsWindow } from "StatsWindow.slint";
export { VirtualKeyboardWindow } from "VirtualKeyboardWindow.slint";
export { WindowBaseConfig } from "WindowBase.slint";
