[package]

name = "rsaber_macros"
edition.workspace = true
description.workspace = true
version.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true
license-file.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]

quote = "1.0.45"
syn = "3.0.0"

[lib]

proc-macro = true

[lints]

workspace = true
