# TODO:
# Build android
# Create release + upload executables/pkgs

name: test

on:
  workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Build pc
      run: |
        cd pc
        cargo build --release
    - name: Build pcvr
      run: |
        cd pcvr
        cargo build --release
